openapi: 3.0.3
info:
  title: UTokyo Online Course Catalogue Api
  version: "2022.10.04"
  description: |
    [東京大学授業カタログ(UTokyo Online Course Catalogue)](https://catalog.he.u-tokyo.ac.jp) Api
    - UTASと違って認証が不要であるため、開発がより楽だと思いますが、授業検索では1度に10件しか取得できません。
    - UTASと同様、HTMLのパースが必要です。
    - Try it outを行うには、CORSを無効化する必要があります。Chrome拡張機能を入れるのがおすすめです。
    - [Allow CORS: Access-Control-Allow-Origin](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf/related?hl=ja)

servers:
  - url: https://catalog.he.u-tokyo.ac.jp

paths:
  /detail:
    description: Get details of given course.
    get:
      tags:
        - Catalog
      parameters:
        - name: code
          in: query
          required: true
          description: 時間割コード
          schema:
            type: string
            example: 30001
        - name: year
          in: query
          required: true
          description: |
            年

            (Wayback Machineによれば、このサイトは2007年から存在していたはずだが、
            基礎統計(30001)で実験したところ、2017年からしか引っ掛からない。)
          schema:
            type: integer
            minimum: 2017
            example: 2022
      responses:
        200:
          description: "OK"
          content:
            "text/html":
              example: ""

  /result:
    description: Get a list of courses that match given conditions.
    get:
      tags:
        - Catalog
      parameters:
        - name: q
          in: query
          required: false
          schema:
            type: string
            example: 睡眠
        - name: type
          in: query
          required: false
          description: |
            機関の分類
              - jd: 学部前期課程
              - ug: 学部後期課程
              - g: 大学院
              - all: 全て機関の分類
          schema:
            type: string
            enum:
              - jd
              - ug
              - g
              - all
            description: |
              - jd: 学部前期課程
              - ug: 学部後期課程
              - g: 大学院
              - all: 全て
        - name: faculty_id
          in: query
          required: false
          description: |
            学部の分類
              - "",0: 指定しない
              - 1-10: 学部後期課程　1:法,2:医,3:工,4:文,5:理,6:農,7:経済,8:教養,9:教育,10:薬
              - 11-25: 大学院　人文社会系研究科-公共政策学教育部
              - 26: 学部前期課程　教養学部（前期課程）
          schema:
            type: string
            example: 0
            maximum: 26
            minimum: 0
            default: 0
        - name: faucet
          in: query
          description: 詳細は最下部を参照
          schema:
            $ref: "#/components/schemas/Faucet"
          required: false
        - name: page
          in: query
          required: true
          description: 1度に10件までしか取得できない
          schema:
            type: integer
            example: 1
            minimum: 1
      responses:
        200:
          description: OK
          content:
            "text/html":
              schema:
                example: ""

components:
  schemas:
    Faucet:
      type: object
      required:
        - ""
      properties:
        uwide_cross_program_codes:
          type: array
          description: 横断型教育プログラム
          items:
            type: string
            example: 21005
        grades:
          type: array
          description: |
            学年
            
            大学院でもこの項目が出現するが、該当する科目は少なく、指定する意味は無いようである。(M1, ...という選択肢はない)
          items:
            type: string
            enum: [B1, B2, B3, B4, B5, B6]
          example: [B1, B2, B3, B4, B5, B6]
        semester_codes:
          type: array
          description: |
            セメスター
            
            学部前期課程用にUTASで使われる"S","A"などは存在しない。
          items:
            type: string
            enum: [S1, S2, A1, A2, W]
          example: [S1, S2, A1, A2, W]
        period_codes:
          type: array
          description: |
            時限
            - 1-49: 時限-1
            - 50: その他
          example: [0, 1, 2, 3, 4, 5, 6, 50]
          items:
            type: string
            enum: [0, 1, 2, 3, 4, 5, 6, 50]
        wday_codes:
          type: array
          description: |
            曜日
            - 1000-1600: 月-日
            - 1700: 集中
          example: ["1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700"]
          items:
            type: string
            enum:
              ["1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700"]
        course_language_codes:
          type: array
          items:
            type: string
            example: 01
        operational_experience_flag:
          type: array
          example: ["true", "false"]
          description: 実務経験のある教員による授業科目
          items:
            type: string
            enum: ["true", "false"]
        subject_code:
          type: array
          items:
            description: |
              分野
              
              [日本十進分類表(NDC)](https://www.libnet.pref.okayama.jp/shiryou/ndc/index.htm)に従う
            type: string
            example: 410
